name: PackCI
on:
  - push
  - pull_request
jobs:
  pack:
    name: Pack Alfred's Workflow
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - uses: WangGuibin/alfred-echo-style@main
      - run: sh packal.sh
