name: PackCI
on:
  - push
  - pull_request
jobs:
  pack:
    name: Pack Alfred's Workflow
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Build and Deploy
        uses: WangGuibin/alfred-echo-style@main
        env:
          PERSONAL_TOKEN: ${{ secrets.ALFREDKEYS }}
          PUBLISH_REPOSITORY: WangGuibin/alfred-echo-style 
          BRANCH: main 
          PUBLISH_DIR: ./
      - run: sh packal.sh
